item {
  name: "resistors"
  id: 1
}
item {
  name: "transistors"
  id: 2
}
item {
  name: "capacitors"
  id: 3
}
item {
  name: "ICs"
  id: 4
}
item {
    name: "diodes"
    id: 5
}
item {
    name: "inductors"
    id: 6
}
item {
    name: "transducers"
    id: 7
}
  